import { Link } from "react-router-dom";
import { courses, recentLessons } from "../data/learning";

export default function DashboardPage() {
  return <div className="dashboard-page">
    <section className="dash-welcome"><div><span className="eyebrow">SATURDAY, 12 SEPTEMBER 2026</span><h1>Good morning, Ankush.</h1><p>Your quantum intuition is getting sharper. Keep the streak alive.</p></div><Link className="button primary" to="/courses/fundamentals">Continue learning <b>↗</b></Link></section>
    <section className="metric-grid"><div className="metric-card featured"><span className="metric-label">OVERALL PROGRESS</span><strong>42<span>%</span></strong><div className="metric-bar"><i style={{ width: "42%" }} /></div><small>+8% this week</small></div><div className="metric-card"><span className="metric-label">LEARNING STREAK</span><strong>07 <small>days</small></strong><div className="week-dots"><i /><i /><i /><i /><i /><i /><i className="empty" /></div><small>Best: 12 days</small></div><div className="metric-card"><span className="metric-label">TIME IN THE LAB</span><strong>04<span>h</span> 36<span>m</span></strong><small>Across 8 sessions</small><div className="sparkline"><i /><i /><i /><i /><i /><i /><i /></div></div><div className="metric-card"><span className="metric-label">QUANTUM LEVEL</span><strong>04 <small>Explorer</small></strong><div className="level-track"><i style={{ width: "68%" }} /></div><small>680 / 1000 XP</small></div></section>
    <div className="dashboard-grid"><section className="dash-panel continue-panel"><div className="panel-topline"><div><span className="eyebrow">PICK UP WHERE YOU LEFT OFF</span><h2>Continue learning</h2></div><Link to="/courses">View all <b>↗</b></Link></div>{recentLessons.map((lesson) => <Link className="lesson-row" to="/courses/fundamentals/lesson/1" key={lesson.lesson}><span className={`lesson-thumb ${lesson.color}`}><b>ψ</b></span><span className="lesson-details"><small>{lesson.course}</small><strong>{lesson.lesson}</strong><span className="inline-progress"><i style={{ width: `${lesson.progress}%` }} /></span></span><span className="lesson-time">{lesson.time}<b>›</b></span></Link>)}</section><section className="dash-panel path-panel"><div className="panel-topline"><div><span className="eyebrow">YOUR LEARNING PATH</span><h2>Quantum foundations</h2></div><span className="completion">72%</span></div><p>Four concepts between you and your first quantum algorithm.</p>{courses.map((course) => <div className="path-row" key={course.id}><span className={`path-dot ${course.accent}`} /> <span>{course.title}</span><strong>{course.progress}%</strong></div>)}<Link className="path-cta" to="/courses/fundamentals">Open learning path <b>↗</b></Link></section></div>
    <section className="recommendation"><div className="rec-icon">✦</div><div><span className="eyebrow">Q-BOT RECOMMENDS</span><h2>Try building a Bell state next.</h2><p>You understand superposition. The next step is seeing two qubits become one shared story.</p></div><Link className="button ghost" to="/quantum-lab">Enter the lab <b>↗</b></Link></section>
  </div>;
}
