import { Link } from "react-router-dom";

export default function HomePage() {
  return <div className="marketing-page">
    <header className="marketing-nav"><Link className="qb-brand" to="/"><span className="qb-mark">Q</span><span><strong>QUANTBITS</strong><small>quantum learning platform</small></span></Link><nav><Link to="/">Home</Link><Link to="/courses">Courses</Link><Link to="/docs">Docs</Link><Link to="/my-learning">My Learning</Link></nav><div><Link className="button primary" to="/my-learning">Start learning <b>↗</b></Link></div></header>
    <main>
      <section className="home-hero"><div className="hero-copy"><span className="eyebrow">THE QUANTUM LEARNING STUDIO</span><h1>Learn the<br /><em>unlearnable.</em></h1><p>Quantum computing is not magic. It is a new way of thinking. Quantbits makes the invisible visible, one experiment at a time.</p><div className="hero-actions"><Link className="button primary" to="/my-learning">Start your path <b>↗</b></Link><Link className="button ghost" to="/courses/fundamentals/learn?tab=lab">Open Quantum Lab <span>⌁</span></Link></div><div className="hero-proof"><span><strong>12k+</strong> curious minds</span><span><strong>48</strong> guided experiments</span><span><strong>Q-BOT</strong> always here</span></div></div><div className="hero-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="hero-core"><span className="core-pulse" /><strong>ψ</strong><small>STATE / 01</small></div><div className="float-label label-alpha">|α|² <b>probability</b></div><div className="float-label label-beta">|β|² <b>amplitude</b></div><div className="hero-grid-line" /></div></section>
      <section className="home-statement" id="experience"><span className="eyebrow">A DIFFERENT KIND OF CLASSROOM</span><h2>Don't just learn what a circuit does.<br /><em>Understand why.</em></h2><div className="statement-grid"><span>01</span><p>Every lesson connects theory to a live circuit, a measured result, and an explanation that meets you where you are.</p><Link to="/courses/fundamentals">Explore the method <b>↗</b></Link></div></section>
      <section className="feature-strip" id="paths"><div><span className="eyebrow">ONE CONTINUOUS LOOP</span><h2>Learn → build → see<br />→ <em>understand.</em></h2></div><div className="feature-steps"><span><b>01</b>Learn the idea</span><span><b>02</b>Build the circuit</span><span><b>03</b>See the state</span><span><b>04</b>Ask Q-BOT</span></div></section>
    </main>
    <footer className="marketing-footer"><span>QUANTBITS / SIH 2026</span><span>Quantum computing, made tangible.</span></footer>
  </div>;
}
