import { Link } from "react-router-dom";

export default function HomePage() {
  return <div className="marketing-page beginner-home">
    <header className="marketing-nav"><Link className="qb-brand" to="/"><span className="qb-mark">Q</span><span><strong>QUANTBITS</strong><small>quantum learning platform</small></span></Link><nav><Link className="active" to="/">Home</Link><Link to="/courses">Courses</Link><Link to="/docs">Docs</Link><Link to="/my-learning">My Learning</Link></nav><div><Link className="button primary" to="/my-learning">My Learning <b>↗</b></Link></div></header>
    <main>
      <section className="beginner-hero"><div className="beginner-hero-copy"><span className="quiet-label">A practical place to learn quantum computing</span><h1>Learn quantum computing by <em>building circuits.</em></h1><p>Start with the basics, try each idea in the Quantum Lab, and ask Q-BOT when something does not make sense.</p><div className="beginner-actions"><Link className="button primary" to="/courses/fundamentals">Start with the basics <b>↗</b></Link><Link className="beginner-text-link" to="/docs">Browse the docs <b>→</b></Link></div></div><div className="beginner-illustration" aria-label="A simple quantum circuit illustration"><div className="illustration-title">Your first circuit</div><div className="simple-circuit"><span className="circuit-wire">q0 <i /> <b>H</b> <i /> <b className="cx">●</b> <i /></span><span className="circuit-wire">q1 <i /> <i /> <b className="target">X</b> <i /></span></div><div className="illustration-caption"><span className="green-dot" /> Build it visually, then run it.</div></div></section>
      <section className="how-section" id="experience"><div className="section-heading"><span className="quiet-label">How it works</span><h2>Three steps from “what is a qubit?”<br />to your first working circuit.</h2></div><div className="how-grid"><article><span className="step-number">01</span><h3>Read</h3><p>Learn one idea at a time with short lessons and clear reference docs.</p><Link to="/courses/fundamentals/learn?tab=lesson&lesson=2">See a lesson <b>→</b></Link></article><article><span className="step-number">02</span><h3>Build</h3><p>Place gates on qubit wires and see what each operation changes.</p><Link to="/courses/fundamentals/learn?tab=lab">Open a guided Lab <b>→</b></Link></article><article><span className="step-number">03</span><h3>Ask</h3><p>Run the circuit and ask Q-BOT to explain the result in plain language.</p><Link to="/my-learning">See My Learning <b>→</b></Link></article></div></section>
      <section className="start-section" id="paths"><div className="section-heading"><span className="quiet-label">Start here</span><h2>One beginner course.<br />A clear first step.</h2></div><div className="start-course"><div className="start-course-badge">Recommended<br /><strong>BEGINNER</strong></div><div className="start-course-copy"><span className="quiet-label">Quantum Computing Fundamentals</span><h3>Understand qubits, superposition, and measurement.</h3><p>Four short modules, interactive examples, and a guided Bell-state circuit in the Lab.</p><div className="start-meta"><span>4 modules</span><span>4h 20m</span><span>No prior experience</span></div></div><Link className="button primary" to="/courses/fundamentals">View course <b>↗</b></Link></div></section>
    </main>
    <footer className="marketing-footer"><span>QUANTBITS / SIH 2026</span><span>Quantum computing, explained clearly.</span></footer>
  </div>;
}
